from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel
from typing import Optional, List
import io
from datetime import datetime

router = APIRouter()

class ReportRequest(BaseModel):
    farmer_name: str = "Farmer"
    farm_location: str = "India"
    land_size_acres: float = 1.0
    top_crop: str = "rice"
    profit_estimate: float = 0
    risk_level: str = "low"
    temperature: float = 25
    rainfall: float = 100
    recommendations: Optional[List[str]] = []

@router.post("/generate_report")
async def generate_report(data: ReportRequest):
    try:
        from reportlab.lib.pagesizes import A4
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
        from reportlab.lib.units import inch

        buffer = io.BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=A4,
                                rightMargin=72, leftMargin=72,
                                topMargin=72, bottomMargin=72)
        styles = getSampleStyleSheet()
        story = []

        # Title
        title_style = ParagraphStyle('Title', parent=styles['Heading1'],
                                     fontSize=24, textColor=colors.HexColor('#2D6A4F'),
                                     spaceAfter=20, alignment=1)
        story.append(Paragraph("🌾 AgriWise AI Farm Report", title_style))
        story.append(Paragraph(f"Generated on {datetime.now().strftime('%d %B %Y')}", styles['Normal']))
        story.append(Spacer(1, 20))

        # Farmer Info
        story.append(Paragraph("👨‍🌾 Farmer Information", styles['Heading2']))
        farmer_data = [
            ["Farmer Name", data.farmer_name],
            ["Farm Location", data.farm_location],
            ["Land Size", f"{data.land_size_acres} acres"],
            ["Report Date", datetime.now().strftime('%d/%m/%Y')],
        ]
        farmer_table = Table(farmer_data, colWidths=[2*inch, 4*inch])
        farmer_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#52B788')),
            ('TEXTCOLOR', (0,0), (0,-1), colors.white),
            ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
            ('FONTSIZE', (0,0), (-1,-1), 11),
            ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
            ('PADDING', (0,0), (-1,-1), 8),
        ]))
        story.append(farmer_table)
        story.append(Spacer(1, 20))

        # Prediction Results
        story.append(Paragraph("🌱 AI Crop Recommendation", styles['Heading2']))
        pred_data = [
            ["Recommended Crop", data.top_crop.title()],
            ["Expected Profit", f"₹{data.profit_estimate:,.0f}"],
            ["Risk Level", data.risk_level.upper()],
            ["Temperature", f"{data.temperature}°C"],
            ["Rainfall", f"{data.rainfall} mm"],
        ]
        pred_table = Table(pred_data, colWidths=[2*inch, 4*inch])
        risk_color = {'low': '#52B788', 'medium': '#F4A261', 'high': '#e74c3c'}.get(data.risk_level, '#52B788')
        pred_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (0,-1), colors.HexColor('#2D6A4F')),
            ('TEXTCOLOR', (0,0), (0,-1), colors.white),
            ('FONTNAME', (0,0), (-1,-1), 'Helvetica'),
            ('FONTSIZE', (0,0), (-1,-1), 11),
            ('GRID', (0,0), (-1,-1), 0.5, colors.grey),
            ('PADDING', (0,0), (-1,-1), 8),
        ]))
        story.append(pred_table)
        story.append(Spacer(1, 20))

        # Recommendations
        if data.recommendations:
            story.append(Paragraph("💡 AI Recommendations", styles['Heading2']))
            for rec in data.recommendations:
                story.append(Paragraph(f"• {rec}", styles['Normal']))
            story.append(Spacer(1, 20))

        # Footer
        footer_style = ParagraphStyle('Footer', parent=styles['Normal'],
                                       fontSize=9, textColor=colors.grey, alignment=1)
        story.append(Paragraph("Generated by AgriWise AI | Smart Agriculture Platform", footer_style))
        story.append(Paragraph("agriwise-backend-evpx.onrender.com", footer_style))

        doc.build(story)
        buffer.seek(0)

        return StreamingResponse(
            buffer,
            media_type="application/pdf",
            headers={"Content-Disposition": f"attachment; filename=agriwise_report_{data.farmer_name}.pdf"}
        )
    except ImportError:
        # Fallback if reportlab not installed
        raise HTTPException(status_code=500, detail="PDF generation not available. Install reportlab.")
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Report generation failed: {str(e)}")

@router.get("/generate_report")
async def generate_report_get(farmer_name: str = "Farmer"):
    """Quick report download via GET"""
    data = ReportRequest(farmer_name=farmer_name)
    return await generate_report(data)
